import 'package:flutter/material.dart';

import 'design_tokens.dart';
import 'style_family.dart';

/// Registry of token packs — add new styles here without rewriting components.
typedef TokenPackBuilder = DesignTokens Function({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
});

class TokenPackRegistry {
  TokenPackRegistry._();

  static final Map<VisualStyleFamily, TokenPackBuilder> _packs = {
    VisualStyleFamily.signature: signaturePack,
    VisualStyleFamily.naturalistic: naturalisticPack,
    VisualStyleFamily.softCute: softCutePack,
    VisualStyleFamily.neoBrutal: neoBrutalPack,
    VisualStyleFamily.aurora: auroraPack,
    VisualStyleFamily.quietFocus: quietFocusPack,
    VisualStyleFamily.dusk: duskPack,
    VisualStyleFamily.harbor: harborPack,
  };

  static DesignTokens resolve({
    required VisualStyleFamily family,
    required bool dark,
    required SpacingDensity spacing,
    required ContrastLevel contrast,
    required bool reducedMotion,
  }) {
    final builder = _packs[family] ?? signaturePack;
    return builder(
      dark: dark,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
    );
  }

  static void register(VisualStyleFamily family, TokenPackBuilder builder) {
    _packs[family] = builder;
  }

  static Iterable<VisualStyleFamily> get registered => _packs.keys;
}

DesignTokens _base({
  required String styleId,
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
  required Color bg,
  required Color bgElevated,
  required Color bgMuted,
  required Color surface,
  required Color surfaceElevated,
  required Color textPrimary,
  required Color textSecondary,
  required Color textMuted,
  required Color border,
  required Color divider,
  required Color primaryAction,
  required Color onPrimaryAction,
  required Color secondaryAccent,
  required Color onSecondaryAccent,
  required Color positive,
  required Color warning,
  required Color urgent,
  required Color destructive,
  required Color focusRing,
  required Color shadowColor,
  required Color decorationAccent,
  required Color pressureCalm,
  required Color pressureWatch,
  required Color pressureTight,
  required Color pressureMissing,
  double radiusSm = 8,
  double radiusMd = 14,
  double radiusLg = 20,
  double radiusXl = 28,
  double cardElevation = 0,
}) {
  var tp = textPrimary;
  var tm = textMuted;
  var ts = textSecondary;
  var b = border;
  if (contrast == ContrastLevel.increased) {
    tp = dark ? const Color(0xFFF8FBF9) : const Color(0xFF0A100E);
    tm = dark ? const Color(0xFFC5D0CA) : const Color(0xFF3A4540);
    ts = dark ? const Color(0xFFE2EAE6) : const Color(0xFF1C2622);
    b = dark ? const Color(0xFFA8B8B0) : const Color(0xFF2A3832);
  }

  return DesignTokens(
    bg: bg,
    bgElevated: bgElevated,
    bgMuted: bgMuted,
    surface: surface,
    surfaceElevated: surfaceElevated,
    textPrimary: tp,
    textSecondary: ts,
    textMuted: tm,
    border: b,
    divider: divider,
    primaryAction: primaryAction,
    onPrimaryAction: onPrimaryAction,
    secondaryAccent: secondaryAccent,
    onSecondaryAccent: onSecondaryAccent,
    positive: positive,
    warning: warning,
    urgent: urgent,
    destructive: destructive,
    focusRing: focusRing,
    shadowColor: shadowColor,
    decorationAccent: decorationAccent,
    pressureCalm: pressureCalm,
    pressureWatch: pressureWatch,
    pressureTight: pressureTight,
    pressureMissing: pressureMissing,
    radiusSm: radiusSm,
    radiusMd: radiusMd,
    radiusLg: radiusLg,
    radiusXl: radiusXl,
    spaceUnit: spacing.spaceUnit,
    cardElevation: cardElevation,
    motionScale: reducedMotion ? 0.0 : 1.0,
    editorialDisplay: 'Manrope',
    bodyFamily: 'Manrope',
    styleId: styleId,
  );
}

DesignTokens signaturePack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'signature',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF1C1610),
      bgElevated: const Color(0xFF261E16),
      bgMuted: const Color(0xFF2E241A),
      surface: const Color(0xFF2A2118),
      surfaceElevated: const Color(0xFF362A20),
      textPrimary: const Color(0xFFF7F1E3),
      textSecondary: const Color(0xFFE0D2B8),
      textMuted: const Color(0xFFB8A48A),
      border: const Color(0xFF4A3A2A),
      divider: const Color(0xFF3A2E22),
      primaryAction: const Color(0xFFE8D0A0),
      onPrimaryAction: const Color(0xFF2A1E12),
      secondaryAccent: const Color(0xFFC4A070),
      onSecondaryAccent: const Color(0xFF1C1610),
      positive: const Color(0xFFB8C48A),
      warning: const Color(0xFFD4B87A),
      urgent: const Color(0xFFD4A090),
      destructive: const Color(0xFFC97A7A),
      focusRing: const Color(0xFFE8D0A0),
      shadowColor: const Color(0x66000000),
      decorationAccent: const Color(0xFFE8D0A0),
      pressureCalm: const Color(0xFFB8C48A),
      pressureWatch: const Color(0xFFD4B87A),
      pressureTight: const Color(0xFFD4A090),
      pressureMissing: const Color(0xFFB8A48A),
      radiusMd: 16,
      radiusLg: 22,
      cardElevation: 2,
    );
  }
  return _base(
    styleId: 'signature',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFF7F1E3),
    bgElevated: const Color(0xFFFFFBF4),
    bgMuted: const Color(0xFFEDE3D0),
    surface: const Color(0xFFFAF4E8),
    surfaceElevated: const Color(0xFFFFFCF6),
    textPrimary: const Color(0xFF3A2E22),
    textSecondary: const Color(0xFF5C4633),
    textMuted: const Color(0xFF8A7460),
    border: const Color(0x33C4A878),
    divider: const Color(0x22C4A878),
    primaryAction: const Color(0xFF8B6A3E),
    onPrimaryAction: const Color(0xFFFFFBF4),
    secondaryAccent: const Color(0xFFB8894A),
    onSecondaryAccent: const Color(0xFFFFFBF4),
    positive: const Color(0xFF6A7A40),
    warning: const Color(0xFF9A6B1F),
    urgent: const Color(0xFFC45A32),
    destructive: const Color(0xFFB3261E),
    focusRing: const Color(0xFF8B6A3E),
    shadowColor: const Color(0x283A2E22),
    decorationAccent: const Color(0xFFE8D9B8),
    pressureCalm: const Color(0xFF6A7A40),
    pressureWatch: const Color(0xFF9A6B1F),
    pressureTight: const Color(0xFFC45A32),
    pressureMissing: const Color(0xFF8A7460),
    radiusMd: 16,
    radiusLg: 22,
    cardElevation: 1,
  );
}

DesignTokens naturalisticPack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'naturalistic',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF0E1612),
      bgElevated: const Color(0xFF162019),
      bgMuted: const Color(0xFF1C2A22),
      surface: const Color(0xFF1A2620),
      surfaceElevated: const Color(0xFF22342B),
      textPrimary: const Color(0xFFF2F6F1),
      textSecondary: const Color(0xFFCDD8CF),
      textMuted: const Color(0xFF8FA894),
      border: const Color(0xFF2E4036),
      divider: const Color(0xFF26362D),
      primaryAction: const Color(0xFF6FA98A),
      onPrimaryAction: const Color(0xFF0A120E),
      secondaryAccent: const Color(0xFFE8B4A0),
      onSecondaryAccent: const Color(0xFF1A100C),
      positive: const Color(0xFF6DA756),
      warning: const Color(0xFFB58A43),
      urgent: const Color(0xFFD4846A),
      destructive: const Color(0xFFCF6B6B),
      focusRing: const Color(0xFF8DE7C0),
      shadowColor: const Color(0x66000000),
      decorationAccent: const Color(0xFF6FA98A),
      pressureCalm: const Color(0xFF6DA756),
      pressureWatch: const Color(0xFFB58A43),
      pressureTight: const Color(0xFFD4846A),
      pressureMissing: const Color(0xFF8FA894),
      radiusLg: 24,
    );
  }
  return _base(
    styleId: 'naturalistic',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFF3EBE3),
    bgElevated: const Color(0xFFF9F4EE),
    bgMuted: const Color(0xFFE8DDD0),
    surface: const Color(0xFFF7F1EA),
    surfaceElevated: const Color(0xFFFFFBF7),
    textPrimary: const Color(0xFF0E1613),
    textSecondary: const Color(0xFF3A4A42),
    textMuted: const Color(0xFF5C6B62),
    border: const Color(0xFF3F5249),
    divider: const Color(0x333F5249),
    primaryAction: const Color(0xFF1F6B4A),
    onPrimaryAction: Colors.white,
    secondaryAccent: const Color(0xFFA85A42),
    onSecondaryAccent: Colors.white,
    positive: const Color(0xFF2F7A4E),
    warning: const Color(0xFF9A6B1F),
    urgent: const Color(0xFFA85A42),
    destructive: const Color(0xFFB3261E),
    focusRing: const Color(0xFF1F6B4A),
    shadowColor: const Color(0x2217201C),
    decorationAccent: const Color(0xFF6FA98A),
    pressureCalm: const Color(0xFF2F7A4E),
    pressureWatch: const Color(0xFF9A6B1F),
    pressureTight: const Color(0xFFA85A42),
    pressureMissing: const Color(0xFF5C6B62),
    radiusLg: 24,
  );
}

DesignTokens softCutePack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'softCute',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF14121A),
      bgElevated: const Color(0xFF1C1924),
      bgMuted: const Color(0xFF24202E),
      surface: const Color(0xFF1E1B28),
      surfaceElevated: const Color(0xFF2A2636),
      textPrimary: const Color(0xFFF7F4FA),
      textSecondary: const Color(0xFFD8D2E0),
      textMuted: const Color(0xFFA398B0),
      border: const Color(0xFF3A3448),
      divider: const Color(0xFF2E2938),
      primaryAction: const Color(0xFFC9A0DC),
      onPrimaryAction: const Color(0xFF1A1020),
      secondaryAccent: const Color(0xFFE8B4A0),
      onSecondaryAccent: const Color(0xFF1A100C),
      positive: const Color(0xFF8FB8A8),
      warning: const Color(0xFFE8C47C),
      urgent: const Color(0xFFE8A0B0),
      destructive: const Color(0xFFE07A8A),
      focusRing: const Color(0xFFC9A0DC),
      shadowColor: const Color(0x55000000),
      decorationAccent: const Color(0xFFC9A0DC),
      pressureCalm: const Color(0xFF8FB8A8),
      pressureWatch: const Color(0xFFE8C47C),
      pressureTight: const Color(0xFFE8A0B0),
      pressureMissing: const Color(0xFFA398B0),
      radiusSm: 12,
      radiusMd: 18,
      radiusLg: 26,
      radiusXl: 36,
    );
  }
  return _base(
    styleId: 'softCute',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFF8F2F6),
    bgElevated: const Color(0xFFFFF9FC),
    bgMuted: const Color(0xFFEFE4EC),
    surface: const Color(0xFFFFF8FB),
    surfaceElevated: const Color(0xFFFFFFFF),
    textPrimary: const Color(0xFF2A2230),
    textSecondary: const Color(0xFF4A4054),
    textMuted: const Color(0xFF7A7088),
    border: const Color(0x33C9A0DC),
    divider: const Color(0x22C9A0DC),
    primaryAction: const Color(0xFF9B6BB0),
    onPrimaryAction: Colors.white,
    secondaryAccent: const Color(0xFFD4846A),
    onSecondaryAccent: Colors.white,
    positive: const Color(0xFF4A8A72),
    warning: const Color(0xFF9A6B1F),
    urgent: const Color(0xFFC45A7A),
    destructive: const Color(0xFFB3261E),
    focusRing: const Color(0xFF9B6BB0),
    shadowColor: const Color(0x1AC9A0DC),
    decorationAccent: const Color(0xFFE8C4DC),
    pressureCalm: const Color(0xFF4A8A72),
    pressureWatch: const Color(0xFF9A6B1F),
    pressureTight: const Color(0xFFC45A7A),
    pressureMissing: const Color(0xFF7A7088),
    radiusSm: 12,
    radiusMd: 18,
    radiusLg: 26,
    radiusXl: 36,
  );
}

DesignTokens neoBrutalPack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'neoBrutal',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF0A0A0A),
      bgElevated: const Color(0xFF141414),
      bgMuted: const Color(0xFF1C1C1C),
      surface: const Color(0xFF161616),
      surfaceElevated: const Color(0xFF222222),
      textPrimary: const Color(0xFFFAFAFA),
      textSecondary: const Color(0xFFE0E0E0),
      textMuted: const Color(0xFFA0A0A0),
      border: const Color(0xFFFAFAFA),
      divider: const Color(0xFF404040),
      primaryAction: const Color(0xFFE8DCC8),
      onPrimaryAction: const Color(0xFF0A0A0A),
      secondaryAccent: const Color(0xFFC4785A),
      onSecondaryAccent: const Color(0xFF0A0A0A),
      positive: const Color(0xFF8FBF9A),
      warning: const Color(0xFFD4B87A),
      urgent: const Color(0xFFC4785A),
      destructive: const Color(0xFFC45A5A),
      focusRing: const Color(0xFFE8DCC8),
      shadowColor: const Color(0xFF000000),
      decorationAccent: const Color(0xFFE8DCC8),
      pressureCalm: const Color(0xFF8FBF9A),
      pressureWatch: const Color(0xFFD4B87A),
      pressureTight: const Color(0xFFC4785A),
      pressureMissing: const Color(0xFFA0A0A0),
      radiusSm: 0,
      radiusMd: 0,
      radiusLg: 4,
      radiusXl: 4,
      cardElevation: 0,
    );
  }
  return _base(
    styleId: 'neoBrutal',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFF5F0E6),
    bgElevated: const Color(0xFFFFFBF2),
    bgMuted: const Color(0xFFE8E0D0),
    surface: const Color(0xFFFFFBF2),
    surfaceElevated: const Color(0xFFFFFFFF),
    textPrimary: const Color(0xFF0A0A0A),
    textSecondary: const Color(0xFF222222),
    textMuted: const Color(0xFF555555),
    border: const Color(0xFF0A0A0A),
    divider: const Color(0xFF0A0A0A),
    primaryAction: const Color(0xFFD4C48A),
    onPrimaryAction: const Color(0xFF0A0A0A),
    secondaryAccent: const Color(0xFFC4785A),
    onSecondaryAccent: const Color(0xFF0A0A0A),
    positive: const Color(0xFF1A7A40),
    warning: const Color(0xFF9A6B00),
    urgent: const Color(0xFFA05030),
    destructive: const Color(0xFFA03030),
    focusRing: const Color(0xFF0A0A0A),
    shadowColor: const Color(0xFF0A0A0A),
    decorationAccent: const Color(0xFFD4C48A),
    pressureCalm: const Color(0xFF1A7A40),
    pressureWatch: const Color(0xFF9A6B00),
    pressureTight: const Color(0xFFCC3300),
    pressureMissing: const Color(0xFF555555),
    radiusSm: 0,
    radiusMd: 0,
    radiusLg: 4,
    radiusXl: 4,
    cardElevation: 0,
  );
}

DesignTokens auroraPack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'aurora',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF12161C),
      bgElevated: const Color(0xFF1A2028),
      bgMuted: const Color(0xFF222830),
      surface: const Color(0xCC1E242C),
      surfaceElevated: const Color(0xE0283038),
      textPrimary: const Color(0xFFF2F5F8),
      textSecondary: const Color(0xFFC8D0D8),
      textMuted: const Color(0xFF8A96A4),
      border: const Color(0x449AADC0),
      divider: const Color(0x332A3340),
      primaryAction: const Color(0xFFB4C4D4),
      onPrimaryAction: const Color(0xFF12161C),
      secondaryAccent: const Color(0xFF9AADC0),
      onSecondaryAccent: const Color(0xFF12161C),
      positive: const Color(0xFFA8C0C8),
      warning: const Color(0xFFD4C48A),
      urgent: const Color(0xFFD4A8A0),
      destructive: const Color(0xFFC89090),
      focusRing: const Color(0xFFB4C4D4),
      shadowColor: const Color(0x5512161C),
      decorationAccent: const Color(0xFF9AADC0),
      pressureCalm: const Color(0xFFA8C0C8),
      pressureWatch: const Color(0xFFD4C48A),
      pressureTight: const Color(0xFFD4A8A0),
      pressureMissing: const Color(0xFF8A96A4),
      radiusLg: 22,
      cardElevation: 4,
    );
  }
  return _base(
    styleId: 'aurora',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFE8EEF2),
    bgElevated: const Color(0xFFF4F7F9),
    bgMuted: const Color(0xFFD8E0E6),
    surface: const Color(0xE6F6F9FB),
    surfaceElevated: const Color(0xF2FFFFFF),
    textPrimary: const Color(0xFF2A3340),
    textSecondary: const Color(0xFF3E4A58),
    textMuted: const Color(0xFF6A7684),
    border: const Color(0x449AADC0),
    divider: const Color(0x229AADC0),
    primaryAction: const Color(0xFF5A7088),
    onPrimaryAction: Colors.white,
    secondaryAccent: const Color(0xFF7A90A4),
    onSecondaryAccent: Colors.white,
    positive: const Color(0xFF5A8088),
    warning: const Color(0xFF9A7B2A),
    urgent: const Color(0xFFC45A48),
    destructive: const Color(0xFFB3261E),
    focusRing: const Color(0xFF5A7088),
    shadowColor: const Color(0x229AADC0),
    decorationAccent: const Color(0xFFC4D2DC),
    pressureCalm: const Color(0xFF5A8088),
    pressureWatch: const Color(0xFF9A7B2A),
    pressureTight: const Color(0xFFC45A48),
    pressureMissing: const Color(0xFF6A7684),
    radiusLg: 22,
    cardElevation: 3,
  );
}

DesignTokens quietFocusPack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'quietFocus',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF0B1220),
      bgElevated: const Color(0xFF121A2C),
      bgMuted: const Color(0xFF182238),
      surface: const Color(0xFF141C2E),
      surfaceElevated: const Color(0xFF1C2840),
      textPrimary: const Color(0xFFE8EEF8),
      textSecondary: const Color(0xFFC0CBDC),
      textMuted: const Color(0xFF7A8AA4),
      border: const Color(0xFF2A3A58),
      divider: const Color(0xFF223048),
      primaryAction: const Color(0xFF6A8CBC),
      onPrimaryAction: const Color(0xFF0B1220),
      secondaryAccent: const Color(0xFF1E3A5F),
      onSecondaryAccent: const Color(0xFFE8EEF8),
      positive: const Color(0xFF7AA8B8),
      warning: const Color(0xFFC4B07A),
      urgent: const Color(0xFFC49080),
      destructive: const Color(0xFFC08080),
      focusRing: const Color(0xFF6A8CBC),
      shadowColor: const Color(0x00000000),
      decorationAccent: const Color(0xFF1E3A5F),
      pressureCalm: const Color(0xFF7AA8B8),
      pressureWatch: const Color(0xFFC4B07A),
      pressureTight: const Color(0xFFC49080),
      pressureMissing: const Color(0xFF7A8AA4),
      radiusSm: 4,
      radiusMd: 8,
      radiusLg: 12,
      radiusXl: 16,
      cardElevation: 0,
    );
  }
  return _base(
    styleId: 'quietFocus',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFF4F6FA),
    bgElevated: const Color(0xFFFFFFFF),
    bgMuted: const Color(0xFFE6EAF2),
    surface: const Color(0xFFFFFFFF),
    surfaceElevated: const Color(0xFFF7F9FC),
    textPrimary: const Color(0xFF0B1220),
    textSecondary: const Color(0xFF1E3A5F),
    textMuted: const Color(0xFF5A6A84),
    border: const Color(0xFFD0D8E4),
    divider: const Color(0xFFE0E6EE),
    primaryAction: const Color(0xFF1E3A5F),
    onPrimaryAction: const Color(0xFFF4F6FA),
    secondaryAccent: const Color(0xFF3A5A88),
    onSecondaryAccent: Colors.white,
    positive: const Color(0xFF2A5A68),
    warning: const Color(0xFF8A7020),
    urgent: const Color(0xFFA05040),
    destructive: const Color(0xFFA03030),
    focusRing: const Color(0xFF1E3A5F),
    shadowColor: const Color(0x0A0B1220),
    decorationAccent: const Color(0xFFD7DEEA),
    pressureCalm: const Color(0xFF2A5A68),
    pressureWatch: const Color(0xFF8A7020),
    pressureTight: const Color(0xFFA05040),
    pressureMissing: const Color(0xFF5A6A84),
    radiusSm: 4,
    radiusMd: 8,
    radiusLg: 12,
    radiusXl: 16,
    cardElevation: 0,
  );
}

DesignTokens duskPack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'dusk',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF1A1428),
      bgElevated: const Color(0xFF241C34),
      bgMuted: const Color(0xFF2C243C),
      surface: const Color(0xFF221A32),
      surfaceElevated: const Color(0xFF2E243E),
      textPrimary: const Color(0xFFF3EAF8),
      textSecondary: const Color(0xFFD4C4E4),
      textMuted: const Color(0xFF9A88B0),
      border: const Color(0xFF4A3A62),
      divider: const Color(0xFF382C4C),
      primaryAction: const Color(0xFFB48AD4),
      onPrimaryAction: const Color(0xFF1A1428),
      secondaryAccent: const Color(0xFFE0A86C),
      onSecondaryAccent: const Color(0xFF1A1428),
      positive: const Color(0xFF8AB8A8),
      warning: const Color(0xFFE0A86C),
      urgent: const Color(0xFFD4848A),
      destructive: const Color(0xFFC06070),
      focusRing: const Color(0xFFB48AD4),
      shadowColor: const Color(0x661A1428),
      decorationAccent: const Color(0xFF6B4E8A),
      pressureCalm: const Color(0xFF8AB8A8),
      pressureWatch: const Color(0xFFE0A86C),
      pressureTight: const Color(0xFFD4848A),
      pressureMissing: const Color(0xFF9A88B0),
      radiusLg: 18,
    );
  }
  return _base(
    styleId: 'dusk',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFF4EEF6),
    bgElevated: const Color(0xFFFBF7FC),
    bgMuted: const Color(0xFFE8DCEC),
    surface: const Color(0xFFFBF7FC),
    surfaceElevated: const Color(0xFFFFFFFF),
    textPrimary: const Color(0xFF2A1838),
    textSecondary: const Color(0xFF4A3460),
    textMuted: const Color(0xFF7A6888),
    border: const Color(0xFFD4C4DC),
    divider: const Color(0xFFE8DCEC),
    primaryAction: const Color(0xFF6B4E8A),
    onPrimaryAction: Colors.white,
    secondaryAccent: const Color(0xFFC4783A),
    onSecondaryAccent: Colors.white,
    positive: const Color(0xFF3A7A68),
    warning: const Color(0xFFA07028),
    urgent: const Color(0xFFB05060),
    destructive: const Color(0xFFA03040),
    focusRing: const Color(0xFF6B4E8A),
    shadowColor: const Color(0x226B4E8A),
    decorationAccent: const Color(0xFFC4A8D4),
    pressureCalm: const Color(0xFF3A7A68),
    pressureWatch: const Color(0xFFA07028),
    pressureTight: const Color(0xFFB05060),
    pressureMissing: const Color(0xFF7A6888),
    radiusLg: 18,
  );
}

DesignTokens harborPack({
  required bool dark,
  required SpacingDensity spacing,
  required ContrastLevel contrast,
  required bool reducedMotion,
}) {
  if (dark) {
    return _base(
      styleId: 'harbor',
      dark: true,
      spacing: spacing,
      contrast: contrast,
      reducedMotion: reducedMotion,
      bg: const Color(0xFF12343C),
      bgElevated: const Color(0xFF1A4048),
      bgMuted: const Color(0xFF224850),
      surface: const Color(0xFF184048),
      surfaceElevated: const Color(0xFF225058),
      textPrimary: const Color(0xFFEEF6F4),
      textSecondary: const Color(0xFFC8DCD8),
      textMuted: const Color(0xFF8AACA8),
      border: const Color(0xFF3A6870),
      divider: const Color(0xFF2A545C),
      primaryAction: const Color(0xFF7EC8C0),
      onPrimaryAction: const Color(0xFF12343C),
      secondaryAccent: const Color(0xFFE4D4B8),
      onSecondaryAccent: const Color(0xFF12343C),
      positive: const Color(0xFF8EC8A8),
      warning: const Color(0xFFE0C080),
      urgent: const Color(0xFFD49080),
      destructive: const Color(0xFFC07070),
      focusRing: const Color(0xFF7EC8C0),
      shadowColor: const Color(0x6612343C),
      decorationAccent: const Color(0xFF3E8A8A),
      pressureCalm: const Color(0xFF8EC8A8),
      pressureWatch: const Color(0xFFE0C080),
      pressureTight: const Color(0xFFD49080),
      pressureMissing: const Color(0xFF8AACA8),
      radiusLg: 16,
    );
  }
  return _base(
    styleId: 'harbor',
    dark: false,
    spacing: spacing,
    contrast: contrast,
    reducedMotion: reducedMotion,
    bg: const Color(0xFFEEF4F2),
    bgElevated: const Color(0xFFF7FBFA),
    bgMuted: const Color(0xFFD8E6E2),
    surface: const Color(0xFFF7FBFA),
    surfaceElevated: const Color(0xFFFFFFFF),
    textPrimary: const Color(0xFF12343C),
    textSecondary: const Color(0xFF2A5058),
    textMuted: const Color(0xFF5A7878),
    border: const Color(0xFFC4D8D4),
    divider: const Color(0xFFD8E6E2),
    primaryAction: const Color(0xFF2A6A6A),
    onPrimaryAction: Colors.white,
    secondaryAccent: const Color(0xFFC4A070),
    onSecondaryAccent: const Color(0xFF12343C),
    positive: const Color(0xFF2A7A58),
    warning: const Color(0xFF9A7820),
    urgent: const Color(0xFFB05040),
    destructive: const Color(0xFFA03838),
    focusRing: const Color(0xFF2A6A6A),
    shadowColor: const Color(0x2212343C),
    decorationAccent: const Color(0xFF8AB8B4),
    pressureCalm: const Color(0xFF2A7A58),
    pressureWatch: const Color(0xFF9A7820),
    pressureTight: const Color(0xFFB05040),
    pressureMissing: const Color(0xFF5A7878),
    radiusLg: 16,
  );
}
