// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9E_IEgksqLswI5omHYx4EPHLsT6Y9QCg',
    appId: '1:34782540195:web:4c140fde2f5f355cc5aa16',
    messagingSenderId: '34782540195',
    projectId: 'study-app-18492',
    authDomain: 'study-app-18492.firebaseapp.com',
    storageBucket: 'study-app-18492.firebasestorage.app',
    measurementId: 'G-714GLNRFR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMm20gGS51JxFHXVqSuiXHgza70CgDT9Y',
    appId: '1:34782540195:android:c8e8afc5216e4711c5aa16',
    messagingSenderId: '34782540195',
    projectId: 'study-app-18492',
    storageBucket: 'study-app-18492.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9E_IEgksqLswI5omHYx4EPHLsT6Y9QCg',
    appId: '1:34782540195:web:e8a1518bd8945d60c5aa16',
    messagingSenderId: '34782540195',
    projectId: 'study-app-18492',
    authDomain: 'study-app-18492.firebaseapp.com',
    storageBucket: 'study-app-18492.firebasestorage.app',
    measurementId: 'G-J3ZFQ0HRL6',
  );

  /// Desktop Firebase C++ SDK uses the same web-style app as Windows.
  static const FirebaseOptions macos = windows;

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9E_IEgksqLswI5omHYx4EPHLsT6Y9QCg',
    appId: '1:34782540195:web:e8a1518bd8945d60c5aa16',
    messagingSenderId: '34782540195',
    projectId: 'study-app-18492',
    authDomain: 'study-app-18492.firebaseapp.com',
    storageBucket: 'study-app-18492.firebasestorage.app',
    iosBundleId: 'com.adaracurry.studygrove',
  );
}
